apiVersion: vmray.broadcom.com/v1alpha1
kind: VMRayCluster
metadata:
  labels:
    app.kubernetes.io/name: vmraycluster
    app.kubernetes.io/instance: vmraycluster-sample
    app.kubernetes.io/part-of: vmray-cluster-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vmray-cluster-operator
  name: vmraycluster-sample
spec:
  # TODO(user): Add fields here
