//go:build !ignore_autogenerated

// Copyright (c) 2024 VMware by Broadcom, Inc. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/vmware-tanzu/vm-operator/api/v1alpha2"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApiServerInfo) DeepCopyInto(out *ApiServerInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApiServerInfo.
func (in *ApiServerInfo) DeepCopy() *ApiServerInfo {
	if in == nil {
		return nil
	}
	out := new(ApiServerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonNodeConfig) DeepCopyInto(out *CommonNodeConfig) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(v1alpha2.VirtualMachineNetworkSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeTypes != nil {
		in, out := &in.NodeTypes, &out.NodeTypes
		*out = make(map[string]NodeType, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SetupCommands != nil {
		in, out := &in.SetupCommands, &out.SetupCommands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InitializationCommands != nil {
		in, out := &in.InitializationCommands, &out.InitializationCommands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonNodeConfig.
func (in *CommonNodeConfig) DeepCopy() *CommonNodeConfig {
	if in == nil {
		return nil
	}
	out := new(CommonNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DockerRegistryConfig) DeepCopyInto(out *DockerRegistryConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DockerRegistryConfig.
func (in *DockerRegistryConfig) DeepCopy() *DockerRegistryConfig {
	if in == nil {
		return nil
	}
	out := new(DockerRegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeadNodeConfig) DeepCopyInto(out *HeadNodeConfig) {
	*out = *in
	if in.SetupCommands != nil {
		in, out := &in.SetupCommands, &out.SetupCommands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(uint)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeadNodeConfig.
func (in *HeadNodeConfig) DeepCopy() *HeadNodeConfig {
	if in == nil {
		return nil
	}
	out := new(HeadNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResource) DeepCopyInto(out *NodeResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResource.
func (in *NodeResource) DeepCopy() *NodeResource {
	if in == nil {
		return nil
	}
	out := new(NodeResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeType) DeepCopyInto(out *NodeType) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeType.
func (in *NodeType) DeepCopy() *NodeType {
	if in == nil {
		return nil
	}
	out := new(NodeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRayCluster) DeepCopyInto(out *VMRayCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRayCluster.
func (in *VMRayCluster) DeepCopy() *VMRayCluster {
	if in == nil {
		return nil
	}
	out := new(VMRayCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMRayCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRayClusterList) DeepCopyInto(out *VMRayClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VMRayCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRayClusterList.
func (in *VMRayClusterList) DeepCopy() *VMRayClusterList {
	if in == nil {
		return nil
	}
	out := new(VMRayClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VMRayClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRayClusterSpec) DeepCopyInto(out *VMRayClusterSpec) {
	*out = *in
	out.ApiServer = in.ApiServer
	in.HeadNode.DeepCopyInto(&out.HeadNode)
	in.WorkerNode.DeepCopyInto(&out.WorkerNode)
	in.NodeConfig.DeepCopyInto(&out.NodeConfig)
	if in.AutoscalerDesiredWorkers != nil {
		in, out := &in.AutoscalerDesiredWorkers, &out.AutoscalerDesiredWorkers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.DockerConfig = in.DockerConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRayClusterSpec.
func (in *VMRayClusterSpec) DeepCopy() *VMRayClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VMRayClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRayClusterStatus) DeepCopyInto(out *VMRayClusterStatus) {
	*out = *in
	in.HeadNodeStatus.DeepCopyInto(&out.HeadNodeStatus)
	if in.CurrentWorkers != nil {
		in, out := &in.CurrentWorkers, &out.CurrentWorkers
		*out = make(map[string]VMRayNodeStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.VMServiceStatus = in.VMServiceStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRayClusterStatus.
func (in *VMRayClusterStatus) DeepCopy() *VMRayClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VMRayClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMRayNodeStatus) DeepCopyInto(out *VMRayNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMRayNodeStatus.
func (in *VMRayNodeStatus) DeepCopy() *VMRayNodeStatus {
	if in == nil {
		return nil
	}
	out := new(VMRayNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMServiceStatus) DeepCopyInto(out *VMServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMServiceStatus.
func (in *VMServiceStatus) DeepCopy() *VMServiceStatus {
	if in == nil {
		return nil
	}
	out := new(VMServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkerNodeConfig) DeepCopyInto(out *WorkerNodeConfig) {
	*out = *in
	if in.SetupCommands != nil {
		in, out := &in.SetupCommands, &out.SetupCommands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkerNodeConfig.
func (in *WorkerNodeConfig) DeepCopy() *WorkerNodeConfig {
	if in == nil {
		return nil
	}
	out := new(WorkerNodeConfig)
	in.DeepCopyInto(out)
	return out
}
