kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vmrayop-clusterrole
rules:
- apiGroups: ["", "rbac.authorization.k8s.io", "vmoperator.vmware.com"] # "" indicates the core API group
  resources: ["serviceaccounts", "serviceaccounts/token", "secrets", "roles", "rolebindings", "virtualmachines", "virtualmachineservices"]
  verbs: ["get", "watch", "list", "create", "delete"]
  # TODO: seperate out rules to create more granular permission, example: we dont need to watch virtualmachineservices.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmrayop-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmrayop-clusterrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: vmw-system-vmrayclusterop
