namespace: vmware-system-rayclusterop

resources:
- ../../webhook
- ../../certmanager

patches:

  # Webhook kustomization.
  - target:
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
    patch: |-
      - op: replace
        path: /metadata/name
        value: vmray-mutating-webhook-config
  - target:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    patch: |-
      - op: replace
        path: /metadata/name
        value: vmray-validating-webhook-config
  - target:
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: vmware-system-rayclusterop/vmray-serving-cert
  - target:
      kind: ValidatingWebhookConfiguration
      name: validating-webhook-configuration
    patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1inject-ca-from
        value: vmware-system-rayclusterop/vmray-serving-cert

  # Certificate kustomization.
  - target:
      kind: Certificate
      name: serving-cert
    patch: |-
      - op: replace
        path: /metadata/name
        value: vmray-serving-cert
  - target:
      kind: Certificate
      name: vmray-serving-cert
    patch: |-
      - op: replace
        path: /spec/dnsNames
        value: [webhook-service.vmware-system-rayclusterop.svc, webhook-service.vmware-system-rayclusterop.svc.cluster.local]

  # Service kustomization.
  - target:
      kind: Service
      name: webhook-service
    patch: |-
      - op: replace
        path: /spec/selector/control-plane
        value: vmray-cluster-controller
