namespace: vmw-system-vmrayclusterop

resources:
- ../../manager/
patches:
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: system
  - target:
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: remove
        path: /spec/template/spec/securityContext
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: default
      - op: replace
        path: /metadata/name
        value: vmray-cluster-controller
      - op: replace
        path: /metadata/labels/control-plane
        value: vmray-cluster-controller
      - op: replace
        path: /spec/selector/matchLabels/control-plane
        value: vmray-cluster-controller
      - op: replace
        path: /spec/template/metadata/labels/control-plane
        value: vmray-cluster-controller
      
  
    

