namespace: vmware-system-rayclusterop

namePrefix: vmray-

resources:
- ../../manager/

patches:
  - path: ../../default/manager_webhook_patch.yaml
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Namespace
      metadata:
        name: system
  - target:
      kind: Deployment
      name: controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: vmray-controller-manager
      - op: replace
        path: /metadata/labels/control-plane
        value: vmray-controller-manager
      - op: replace
        path: /spec/selector/matchLabels/control-plane
        value: vmray-controller-manager
      - op: replace
        path: /spec/template/metadata/labels/control-plane
        value: vmray-controller-manager
